In [151]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [153]:
data = pd.read_csv('capaign data.csv')

In [155]:
data.head()

,Campaign_ID,Campaign_Name,Start_Date,End_Date,Channel,Impressions,Clicks,Spend,Conversions,Active,Clicks,Campaign_Tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [157]:
data.shape

(2020, 12)

In [159]:
data.columns

Index([' Campaign_ID ', 'Campaign_Name', 'Start_Date', 'End_Date', 'Channel',
       'Impressions', 'Clicks ', 'Spend', 'Conversions', 'Active', 'Clicks',
       'Campaign_Tag'],
      dtype='object')

In [161]:
data.isnull().sum()

 Campaign_ID        0
Campaign_Name       0
Start_Date          0
End_Date            0
Channel           101
Impressions         0
Clicks              0
Spend               0
Conversions       200
Active              0
Clicks           1980
Campaign_Tag        0
dtype: int64

In [163]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0    Campaign_ID   2020 non-null   object
 1   Campaign_Name  2020 non-null   object
 2   Start_Date     2020 non-null   object
 3   End_Date       2020 non-null   object
 4   Channel        1919 non-null   object
 5   Impressions    2020 non-null   int64
 6   Clicks         2020 non-null   int64
 7   Spend          2020 non-null   object
 8   Conversions    1820 non-null   float64
 9   Active         2020 non-null   object
 10  Clicks         40 non-null     float64
 11  Campaign_Tag   2020 non-null   object
dtypes: float64(2), int64(2), object(8)
memory usage: 189.5+ KB

In [165]:
data.describe()

        Impressions      Clicks   Conversions        Clicks
count   2020.000000  2020.000000  1820.000000     40.000000
mean   49839.896040  1500.744059   186.085714  54856.200000
std    28579.637473  1084.765654   160.129172  30552.773369
min     1055.000000    11.000000     0.000000   2508.000000
25%    25033.500000   650.750000    68.000000  30164.750000
50%    50097.500000  1245.000000   142.000000  57707.500000
75%    74784.250000  2185.250000   257.000000  81497.500000
max    99875.000000  4812.000000   943.000000  99483.000000

In [167]:
data.columns = data.columns.str.strip().str.lower().str.replace(' ', '')

In [169]:
data.columns

Index(['campaign_id', 'campaign_name', 'start_date', 'end_date', 'channel',
       'impressions', 'clicks', 'spend', 'conversions', 'active', 'clicks',
       'campaign_tag'],
      dtype='object')

In [171]:
data.head()

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,$102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [173]:
dirty_spend_mask = data['spend'].astype('str').str.contains('\$')
print(data.loc[dirty_spend_mask, ['campaign_id', 'spend']].head(3))

   campaign_id     spend
0    CMP-00001   $102.82
21   CMP-00022   $2428.4
22   CMP-00023  $4726.22

In [175]:
data['spend'] = data['spend'].astype('str').str.replace(r'[^\d.-]', '', regex = True)

In [177]:
print(data.loc[dirty_spend_mask, ['campaign_id', 'spend']].head(3))

   campaign_id    spend
0    CMP-00001   102.82
21   CMP-00022   2428.4
22   CMP-00023  4726.22

In [179]:
data['spend'] = data['spend'].astype('float')

In [181]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   campaign_id    2020 non-null   object
 1   campaign_name  2020 non-null   object
 2   start_date     2020 non-null   object
 3   end_date       2020 non-null   object
 4   channel        1919 non-null   object
 5   impressions    2020 non-null   int64
 6   clicks         2020 non-null   int64
 7   spend          2020 non-null   float64
 8   conversions    1820 non-null   float64
 9   active         2020 non-null   object
 10  clicks         40 non-null     float64
 11  campaign_tag   2020 non-null   object
dtypes: float64(3), int64(2), object(7)
memory usage: 189.5+ KB

In [183]:
data['channel'].nunique()

10

In [185]:
data['channel'].unique()

array(['TikTok', 'Facebook', 'Email', 'Instagram', 'Google Ads', 'E-mail',
       nan, 'Gogle', 'Tik_Tok', 'Facebok', 'Insta_gram'], dtype=object)

In [187]:
data['channel'].value_counts()

channel
TikTok        399
Facebook      391
Email         359
Google Ads    346
Instagram     340
E-mail         21
Insta_gram     19
Tik_Tok        16
Gogle          14
Facebok        14
Name: count, dtype: int64

In [189]:
cleanup_map = {
    'Tik_Tok' : 'TikTok',
     'Facebok' : 'Facebook',
    'Insta_gram' : 'Instagram',
    'Gogle' : 'Google Ads',
    'E-mail' : 'Email',
    'N/A' : np.nan
}

In [191]:
data['channel'] = data['channel'].replace(cleanup_map)

In [193]:
data['channel'].value_counts()

channel
TikTok        415
Facebook      405
Email         380
Google Ads    360
Instagram     359
Name: count, dtype: int64

In [195]:
data.head()

,campaign_id,campaign_name,start_date,end_date,channel,impressions,clicks,spend,conversions,active,clicks,campaign_tag
0,CMP-00001,Q4_Summer_CMP-00001,2023-11-24 00:00:00,2023-12-13,TikTok,16795,197,102.82,20.0,Y,NaN,TI
1,CMP-00002,Q1_Launch_CMP-00002,2023-05-06 00:00:00,2023-05-12,Facebook,1860,30,24.33,1.0,0,NaN,FA
2,CMP-00003,Q3_Winter_CMP-00003,2023-12-13 00:00:00,2023-12-20,Email,77820,843,1323.39,51.0,No,NaN,EM
3,CMP-00004,Q1_BlackFriday_CMP-00004,2023-10-30,2023-11-03,TikTok,55886,2019,2180.38,135.0,True,NaN,TI
4,CMP-00005,Q2_Winter_CMP-00005,2023-04-22 00:00:00,2023-04-23,Facebook,7265,169,252.44,30.0,Yes,NaN,FA

In [197]:
data['active'].nunique()

7

In [199]:
data['active'].unique()

array(['Y', '0', 'No', 'True', 'Yes', '1', 'False'], dtype=object)

In [201]:
data['active'].value_counts()

active
1        319
Yes      306
True     297
No       291
False    281
Y        273
0        253
Name: count, dtype: int64

In [203]:
cleanedup_map = {
    '1' : 'Yes',
    'True' : 'Yes',
    "Y" : 'Yes',
    '0' : 'No',
    'False' : 'No',
    1 : 'Yes'
}
data['active'] = data['active'].replace(cleanedup_map)
data['active'].value_counts()

active
Yes    1195
No      825
Name: count, dtype: int64

In [205]:
data['start_date'].dtype

dtype('O')

In [207]:
data['start_date'] = pd.to_datetime(data['start_date'], errors = 'coerce')
data['end_date'] = pd.to_datetime(data['end_date'], dayfirst = True, errors = 'coerce')
data['start_date'].dtype

dtype('<M8[ns]')

In [223]:
data = data.loc[:, ~data.columns.duplicated()]
impossible_mask = data['clicks'] > data['impressions']
print(data.loc[impossible_mask, ['campaign_id', 'impressions', 'clicks']].head())

Empty DataFrame
Columns: [campaign_id, impressions, clicks]
Index: []

In [227]:
time_travel_mask = data['end_date'] < data['start_date']
print(data.loc[time_travel_mask, ['campaign_id', 'end_date', 'start_date']].head())
data.loc[time_travel_mask, 'end_date'] = data.loc[time_travel_mask, 'start_date'] + pd.Timedelta(days = 30)
print(data.loc[time_travel_mask, ['campaign_id', 'end_date', 'start_date']].head())

    campaign_id   end_date start_date
23    CMP-00024 2023-05-01 2023-05-06
54    CMP-00055 2023-08-27 2023-09-01
71    CMP-00072 2023-01-27 2023-02-01
156   CMP-00157 2023-12-01 2023-12-06
200   CMP-00201 2023-01-06 2023-01-11
    campaign_id   end_date start_date
23    CMP-00024 2023-06-05 2023-05-06
54    CMP-00055 2023-10-01 2023-09-01
71    CMP-00072 2023-03-03 2023-02-01
156   CMP-00157 2024-01-05 2023-12-06
200   CMP-00201 2023-02-10 2023-01-11

In [238]:
Q1 = data['spend'].quantile(0.25)
Q3 = data['spend'].quantile(0.75)
IQR = Q3 - Q1
upper_limit = Q3 + (3 * IQR)
outlier_mask = data['spend'] > upper_limit
print(data.loc[outlier_mask, ['campaign_id', 'spend']].head(5))
data.loc[outlier_mask, 'spend'] = upper_limit
print(data.loc[outlier_mask, ['campaign_id', 'spend']].head(5))

     campaign_id      spend
789    CMP-00790  500000.00
1443   CMP-01444    8921.51
1460   CMP-01461  500000.00
1718   CMP-01719  500000.00
1754   CMP-01755  500000.00
     campaign_id      spend
789    CMP-00790  8603.5375
1443   CMP-01444  8603.5375
1460   CMP-01461  8603.5375
1718   CMP-01719  8603.5375
1754   CMP-01755  8603.5375